<?xml version="1.0"?>
<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	      <!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
	      <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>Data_Extract_From_World_Development_Indicators_Data-weka.filters.unsupervised.instance.SubsetByExpression-ECLASS is &apos;LCN&apos;-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R1-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R2-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R3-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R4-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R5-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R6-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R7-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R8-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R9-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R10-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R11-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R12-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R13-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R14-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R15-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R16-unset-class-temporarily-weka.filters.unsupervised.attribute.Reorder-R12,5,11,7,6,14,8,16,3,15,4,1,10,13,9,2-weka.filters.unsupervised.attribute.ReplaceMissingValues</NAME>
<VARIABLE TYPE="nature">
<NAME>GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</NAME>
<OUTCOME>&apos;(-inf-11545.334857]&apos;</OUTCOME>
<OUTCOME>&apos;(11545.334857-13205.180675]&apos;</OUTCOME>
<OUTCOME>&apos;(13205.180675-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</NAME>
<OUTCOME>&apos;(-inf-32.025803]&apos;</OUTCOME>
<OUTCOME>&apos;(32.025803-38.220216]&apos;</OUTCOME>
<OUTCOME>&apos;(38.220216-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Industry, value added (% of GDP) [NV.IND.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-33.621308]&apos;</OUTCOME>
<OUTCOME>&apos;(33.621308-37.346045]&apos;</OUTCOME>
<OUTCOME>&apos;(37.346045-inf)&apos;</OUTCOME>
<PROPERTY>position = (-217,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Services, etc., value added (% of GDP) [NV.SRV.TETC.ZS]</NAME>
<OUTCOME>&apos;(-inf-54.194888]&apos;</OUTCOME>
<OUTCOME>&apos;(54.194888-59.544635]&apos;</OUTCOME>
<OUTCOME>&apos;(59.544635-inf)&apos;</OUTCOME>
<PROPERTY>position = (-652,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Agriculture, value added (% of GDP) [NV.AGR.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-8.699617]&apos;</OUTCOME>
<OUTCOME>&apos;(8.699617-12.42395]&apos;</OUTCOME>
<OUTCOME>&apos;(12.42395-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]</NAME>
<OUTCOME>&apos;(-inf-18.397787]&apos;</OUTCOME>
<OUTCOME>&apos;(18.397787-22.486907]&apos;</OUTCOME>
<OUTCOME>&apos;(22.486907-inf)&apos;</OUTCOME>
<PROPERTY>position = (-435,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Trademark applications, total [IP.TMK.TOTL]</NAME>
<OUTCOME>&apos;(-inf-208420.333333]&apos;</OUTCOME>
<OUTCOME>&apos;(208420.333333-344717.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(344717.666667-inf)&apos;</OUTCOME>
<PROPERTY>position = (-272,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Scientific and technical journal articles [IP.JRN.ARTC.SC]</NAME>
<OUTCOME>&apos;(-inf-10965.351612]&apos;</OUTCOME>
<OUTCOME>&apos;(10965.351612-18391.703223]&apos;</OUTCOME>
<OUTCOME>&apos;(18391.703223-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</NAME>
<OUTCOME>&apos;(-inf-11545.334857]&apos;</OUTCOME>
<OUTCOME>&apos;(11545.334857-13205.180675]&apos;</OUTCOME>
<OUTCOME>&apos;(13205.180675-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</NAME>
<OUTCOME>&apos;(-inf-0.894157]&apos;</OUTCOME>
<OUTCOME>&apos;(0.894157-4.486585]&apos;</OUTCOME>
<OUTCOME>&apos;(4.486585-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</NAME>
<OUTCOME>&apos;(-inf-28.143601]&apos;</OUTCOME>
<OUTCOME>&apos;(28.143601-34.205574]&apos;</OUTCOME>
<OUTCOME>&apos;(34.205574-inf)&apos;</OUTCOME>
<PROPERTY>position = (-362,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</NAME>
<OUTCOME>&apos;(-inf-0.894157]&apos;</OUTCOME>
<OUTCOME>&apos;(0.894157-4.486585]&apos;</OUTCOME>
<OUTCOME>&apos;(4.486585-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</NAME>
<OUTCOME>&apos;(-inf-14.516904]&apos;</OUTCOME>
<OUTCOME>&apos;(14.516904-17.529588]&apos;</OUTCOME>
<OUTCOME>&apos;(17.529588-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]</NAME>
<OUTCOME>&apos;(-inf-11.105816]&apos;</OUTCOME>
<OUTCOME>&apos;(11.105816-13.338031]&apos;</OUTCOME>
<OUTCOME>&apos;(13.338031-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Net official development assistance and official aid received (constant 2012 US$) [DT.ODA.ALLD.KD]</NAME>
<OUTCOME>&apos;(-inf-3873696666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(3873696666.666667-7747393333.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(7747393333.333334-inf)&apos;</OUTCOME>
<PROPERTY>position = (-816,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Unemployment, total (% of total labor force) [SL.UEM.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-7.207485]&apos;</OUTCOME>
<OUTCOME>&apos;(7.207485-8.161523]&apos;</OUTCOME>
<OUTCOME>&apos;(8.161523-inf)&apos;</OUTCOME>
<PROPERTY>position = (-870,512)</PROPERTY>
</VARIABLE>
<DEFINITION>
<FOR>GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</FOR>
<TABLE>
0.7777777777777778 0.0707070707070707 0.15151515151515152 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</FOR>
<TABLE>
0.9191919191919192 0.050505050505050504 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Industry, value added (% of GDP) [NV.IND.TOTL.ZS]</FOR>
<TABLE>
0.29292929292929293 0.41414141414141414 0.29292929292929293 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Services, etc., value added (% of GDP) [NV.SRV.TETC.ZS]</FOR>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<GIVEN>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</GIVEN>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<TABLE>
0.6708860759493671 0.13924050632911392 0.189873417721519 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.07692307692307693 0.07692307692307693 0.8461538461538461 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Agriculture, value added (% of GDP) [NV.AGR.TOTL.ZS]</FOR>
<TABLE>
0.5353535353535354 0.29292929292929293 0.1717171717171717 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]</FOR>
<GIVEN>Trademark applications, total [IP.TMK.TOTL]</GIVEN>
<TABLE>
0.05660377358490566 0.018867924528301886 0.9245283018867925 
0.3333333333333333 0.4074074074074074 0.25925925925925924 
0.84 0.12 0.04 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Trademark applications, total [IP.TMK.TOTL]</FOR>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<TABLE>
0.5604395604395604 0.25274725274725274 0.18681318681318682 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Scientific and technical journal articles [IP.JRN.ARTC.SC]</FOR>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<TABLE>
0.7582417582417582 0.12087912087912088 0.12087912087912088 
0.6 0.2 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</FOR>
<TABLE>
0.797979797979798 0.050505050505050504 0.15151515151515152 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</FOR>
<TABLE>
0.13131313131313133 0.47474747474747475 0.3939393939393939 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</FOR>
<TABLE>
0.9191919191919192 0.050505050505050504 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</FOR>
<TABLE>
0.15151515151515152 0.45454545454545453 0.3939393939393939 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</FOR>
<TABLE>
0.9393939393939394 0.030303030303030304 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]</FOR>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<TABLE>
0.4065934065934066 0.25274725274725274 0.34065934065934067 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Net official development assistance and official aid received (constant 2012 US$) [DT.ODA.ALLD.KD]</FOR>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<TABLE>
0.054945054945054944 0.5604395604395604 0.38461538461538464 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Unemployment, total (% of total labor force) [SL.UEM.TOTL.ZS]</FOR>
<TABLE>
0.7171717171717171 0.15151515151515152 0.13131313131313133 
</TABLE>
</DEFINITION>
</NETWORK>
</BIF>
