<?xml version="1.0"?>
<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	      <!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
	      <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>Data_Extract_From_World_Development_Indicators_Data-weka.filters.unsupervised.instance.SubsetByExpression-ECLASS is &apos;SRB&apos;-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R15-weka.filters.unsupervised.attribute.Remove-R17-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R1-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R2-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R3-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R4-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R5-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R6-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R7-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R8-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R9-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R10-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R11-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R12-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R13-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R14-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R15-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-F-B3-M-1.0-R16-unset-class-temporarily-weka.filters.unsupervised.attribute.Reorder-R11,13,8,16,6,1,12,3,7,14,4-5,10,15,9,2-weka.filters.unsupervised.attribute.ReplaceMissingValues</NAME>
<VARIABLE TYPE="nature">
<NAME>Services, etc., value added (% of GDP) [NV.SRV.TETC.ZS]</NAME>
<OUTCOME>&apos;(-inf-51.150651]&apos;</OUTCOME>
<OUTCOME>&apos;(51.150651-60.161228]&apos;</OUTCOME>
<OUTCOME>&apos;(60.161228-inf)&apos;</OUTCOME>
<PROPERTY>position = (-652,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</NAME>
<OUTCOME>&apos;(-inf-18.85]&apos;</OUTCOME>
<OUTCOME>&apos;(18.85-20.2]&apos;</OUTCOME>
<OUTCOME>&apos;(20.2-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Trademark applications, total [IP.TMK.TOTL]</NAME>
<OUTCOME>&apos;(-inf-6932]&apos;</OUTCOME>
<OUTCOME>&apos;(6932-9072.5]&apos;</OUTCOME>
<OUTCOME>&apos;(9072.5-inf)&apos;</OUTCOME>
<PROPERTY>position = (-272,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Agriculture, value added (% of GDP) [NV.AGR.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-10.509582]&apos;</OUTCOME>
<OUTCOME>&apos;(10.509582-19.182865]&apos;</OUTCOME>
<OUTCOME>&apos;(19.182865-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Net official development assistance and official aid received (constant 2012 US$) [DT.ODA.ALLD.KD]</NAME>
<OUTCOME>&apos;(-inf-709715000]&apos;</OUTCOME>
<OUTCOME>&apos;(709715000-1357405000]&apos;</OUTCOME>
<OUTCOME>&apos;(1357405000-inf)&apos;</OUTCOME>
<PROPERTY>position = (-816,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</NAME>
<OUTCOME>&apos;(-inf-1.91381]&apos;</OUTCOME>
<OUTCOME>&apos;(1.91381-5.453555]&apos;</OUTCOME>
<OUTCOME>&apos;(5.453555-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</NAME>
<OUTCOME>&apos;(-inf-8433.101326]&apos;</OUTCOME>
<OUTCOME>&apos;(8433.101326-12240.37064]&apos;</OUTCOME>
<OUTCOME>&apos;(12240.37064-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Scientific and technical journal articles [IP.JRN.ARTC.SC]</NAME>
<OUTCOME>&apos;(-inf-1050]&apos;</OUTCOME>
<OUTCOME>&apos;(1050-1168.95]&apos;</OUTCOME>
<OUTCOME>&apos;(1168.95-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</NAME>
<OUTCOME>&apos;(-inf-1.91381]&apos;</OUTCOME>
<OUTCOME>&apos;(1.91381-5.453555]&apos;</OUTCOME>
<OUTCOME>&apos;(5.453555-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</NAME>
<OUTCOME>&apos;(-inf-57.75]&apos;</OUTCOME>
<OUTCOME>&apos;(57.75-59]&apos;</OUTCOME>
<OUTCOME>&apos;(59-inf)&apos;</OUTCOME>
<PROPERTY>position = (-362,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Industry, value added (% of GDP) [NV.IND.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-29.651348]&apos;</OUTCOME>
<OUTCOME>&apos;(29.651348-31.886633]&apos;</OUTCOME>
<OUTCOME>&apos;(31.886633-inf)&apos;</OUTCOME>
<PROPERTY>position = (-217,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]</NAME>
<OUTCOME>&apos;(-inf-18.338358]&apos;</OUTCOME>
<OUTCOME>&apos;(18.338358-19.497605]&apos;</OUTCOME>
<OUTCOME>&apos;(19.497605-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</NAME>
<OUTCOME>&apos;(-inf-8433.101326]&apos;</OUTCOME>
<OUTCOME>&apos;(8433.101326-12240.37064]&apos;</OUTCOME>
<OUTCOME>&apos;(12240.37064-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</NAME>
<OUTCOME>&apos;(-inf-19.55]&apos;</OUTCOME>
<OUTCOME>&apos;(19.55-33.85]&apos;</OUTCOME>
<OUTCOME>&apos;(33.85-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Unemployment, total (% of total labor force) [SL.UEM.TOTL.ZS]</NAME>
<OUTCOME>&apos;(-inf-13.75]&apos;</OUTCOME>
<OUTCOME>&apos;(13.75-18.85]&apos;</OUTCOME>
<OUTCOME>&apos;(18.85-inf)&apos;</OUTCOME>
<PROPERTY>position = (-870,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]</NAME>
<OUTCOME>&apos;(-inf-17.032837]&apos;</OUTCOME>
<OUTCOME>&apos;(17.032837-20.752895]&apos;</OUTCOME>
<OUTCOME>&apos;(20.752895-inf)&apos;</OUTCOME>
<PROPERTY>position = (-435,512)</PROPERTY>
</VARIABLE>
<DEFINITION>
<FOR>Services, etc., value added (% of GDP) [NV.SRV.TETC.ZS]</FOR>
<GIVEN>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</GIVEN>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<GIVEN>Trademark applications, total [IP.TMK.TOTL]</GIVEN>
<GIVEN>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</GIVEN>
<GIVEN>Scientific and technical journal articles [IP.JRN.ARTC.SC]</GIVEN>
<TABLE>
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.8390804597701149 0.12643678160919541 0.034482758620689655 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</FOR>
<TABLE>
0.9191919191919192 0.050505050505050504 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Trademark applications, total [IP.TMK.TOTL]</FOR>
<TABLE>
0.050505050505050504 0.898989898989899 0.050505050505050504 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Agriculture, value added (% of GDP) [NV.AGR.TOTL.ZS]</FOR>
<GIVEN>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</GIVEN>
<TABLE>
0.013333333333333334 0.8133333333333334 0.17333333333333334 
0.4117647058823529 0.5294117647058824 0.058823529411764705 
0.5384615384615384 0.38461538461538464 0.07692307692307693 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Net official development assistance and official aid received (constant 2012 US$) [DT.ODA.ALLD.KD]</FOR>
<TABLE>
0.7373737373737373 0.13131313131313133 0.13131313131313133 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</FOR>
<TABLE>
0.1111111111111111 0.7575757575757576 0.13131313131313133 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</FOR>
<GIVEN>Trademark applications, total [IP.TMK.TOTL]</GIVEN>
<GIVEN>Scientific and technical journal articles [IP.JRN.ARTC.SC]</GIVEN>
<TABLE>
0.2 0.2 0.6 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.8390804597701149 0.12643678160919541 0.034482758620689655 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.42857142857142855 0.42857142857142855 
0.2 0.2 0.6 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Scientific and technical journal articles [IP.JRN.ARTC.SC]</FOR>
<TABLE>
0.898989898989899 0.050505050505050504 0.050505050505050504 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous GDP growth (annual %) [NY.GDP.MKTP.KD.ZG]</FOR>
<TABLE>
0.1111111111111111 0.7575757575757576 0.13131313131313133 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with secondary education (% of total) [SL.TLF.SECO.ZS]</FOR>
<TABLE>
0.9191919191919192 0.050505050505050504 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Industry, value added (% of GDP) [NV.IND.TOTL.ZS]</FOR>
<TABLE>
0.7373737373737373 0.13131313131313133 0.13131313131313133 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>General government final consumption expenditure (% of GDP) [NE.CON.GOVT.ZS]</FOR>
<TABLE>
0.7373737373737373 0.13131313131313133 0.13131313131313133 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous GDP per capita, PPP (constant 2011 international $) [NY.GDP.PCAP.PP.KD]</FOR>
<TABLE>
0.7373737373737373 0.15151515151515152 0.1111111111111111 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Labor force with primary education (% of total) [SL.TLF.PRIM.ZS]</FOR>
<TABLE>
0.9191919191919192 0.050505050505050504 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Unemployment, total (% of total labor force) [SL.UEM.TOTL.ZS]</FOR>
<GIVEN>Trademark applications, total [IP.TMK.TOTL]</GIVEN>
<GIVEN>Labor force with tertiary education (% of total) [SL.TLF.TERT.ZS]</GIVEN>
<TABLE>
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.2 0.2 0.6 
0.7752808988764045 0.14606741573033707 0.07865168539325842 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.42857142857142855 0.42857142857142855 0.14285714285714285 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Manufacturing, value added (% of GDP) [NV.IND.MANF.ZS]</FOR>
<TABLE>
0.7373737373737373 0.13131313131313133 0.13131313131313133 
</TABLE>
</DEFINITION>
</NETWORK>
</BIF>
