<?xml version="1.0"?>
<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	      <!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
	      <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>smets woulters data-weka.filters.unsupervised.instance.SubsetByExpression-ECLASS is &apos;NIC&apos;-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R6-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R1-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R2-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R3-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R4-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R5-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R6-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R7-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R8-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R9-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R10-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R11-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R12-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R13-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R14-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R15-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R16-unset-class-temporarily-weka.filters.unsupervised.attribute.Reorder-R1,6,13,2,11,3,16,15,5,7,10,14,12,8-9,4-weka.filters.unsupervised.attribute.ReplaceMissingValues</NAME>
<VARIABLE TYPE="nature">
<NAME>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>&apos;(-inf-98363754509.126992]&apos;</OUTCOME>
<OUTCOME>&apos;(98363754509.126992-123370386847.047488]&apos;</OUTCOME>
<OUTCOME>&apos;(123370386847.047488-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP (constant LCU) [NY.GDP.MKTP.KN]</NAME>
<OUTCOME>&apos;(-inf-79692923075.7168]&apos;</OUTCOME>
<OUTCOME>&apos;(79692923075.7168-119016623987.8584]&apos;</OUTCOME>
<OUTCOME>&apos;(119016623987.8584-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>&apos;(-inf-4558223733.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(4558223733.333334-9093997466.666666]&apos;</OUTCOME>
<OUTCOME>&apos;(9093997466.666666-inf)&apos;</OUTCOME>
<PROPERTY>position = (-362,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>&apos;(-inf-1495666666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(1495666666.666667-2988533333.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(2988533333.333334-inf)&apos;</OUTCOME>
<PROPERTY>position = (-652,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>&apos;(-inf--33666666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(-33666666.666667-93366666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(93366666.666667-inf)&apos;</OUTCOME>
<PROPERTY>position = (-362,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-27169171981.666668]&apos;</OUTCOME>
<OUTCOME>&apos;(27169171981.666668-54504963964.333336]&apos;</OUTCOME>
<OUTCOME>&apos;(54504963964.333336-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-27169171981.666668]&apos;</OUTCOME>
<OUTCOME>&apos;(27169171981.666668-54504963964.333336]&apos;</OUTCOME>
<OUTCOME>&apos;(54504963964.333336-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</NAME>
<OUTCOME>&apos;(-inf-51.033333]&apos;</OUTCOME>
<OUTCOME>&apos;(51.033333-56.066666]&apos;</OUTCOME>
<OUTCOME>&apos;(56.066666-inf)&apos;</OUTCOME>
<PROPERTY>position = (-435,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Exogenous spending</NAME>
<OUTCOME>&apos;(-inf-36385416006.544664]&apos;</OUTCOME>
<OUTCOME>&apos;(36385416006.544664-60739334753.272328]&apos;</OUTCOME>
<OUTCOME>&apos;(60739334753.272328-inf)&apos;</OUTCOME>
<PROPERTY>position = (-870,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</NAME>
<OUTCOME>&apos;(-inf-3199706535.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(3199706535.666667-6399403198.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(6399403198.333334-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Capital-labour ratio</NAME>
<OUTCOME>&apos;(-inf-4.64539]&apos;</OUTCOME>
<OUTCOME>&apos;(4.64539-7.94735]&apos;</OUTCOME>
<OUTCOME>&apos;(7.94735-inf)&apos;</OUTCOME>
<PROPERTY>position = (-816,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>&apos;(-inf--33666666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(-33666666.666667-93366666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(93366666.666667-inf)&apos;</OUTCOME>
<PROPERTY>position = (-217,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>&apos;(-inf-4558223733.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(4558223733.333334-9093997466.666666]&apos;</OUTCOME>
<OUTCOME>&apos;(9093997466.666666-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Lending interest rate (%) [FR.INR.LEND]</NAME>
<OUTCOME>&apos;(-inf-40642.35189]&apos;</OUTCOME>
<OUTCOME>&apos;(40642.35189-81274.165945]&apos;</OUTCOME>
<OUTCOME>&apos;(81274.165945-inf)&apos;</OUTCOME>
<PROPERTY>position = (-272,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>&apos;(-inf-98363754509.126992]&apos;</OUTCOME>
<OUTCOME>&apos;(98363754509.126992-123370386847.047488]&apos;</OUTCOME>
<OUTCOME>&apos;(123370386847.047488-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>&apos;(-inf-1495666666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(1495666666.666667-2988533333.333334]&apos;</OUTCOME>
<OUTCOME>&apos;(2988533333.333334-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,256)</PROPERTY>
</VARIABLE>
<DEFINITION>
<FOR>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<TABLE>
0.13131313131313133 0.1111111111111111 0.7575757575757576 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP (constant LCU) [NY.GDP.MKTP.KN]</FOR>
<GIVEN>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</GIVEN>
<GIVEN>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</GIVEN>
<TABLE>
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.45454545454545453 0.45454545454545453 0.09090909090909091 
0.07692307692307693 0.6923076923076923 0.23076923076923078 
0.4647887323943662 0.4084507042253521 0.1267605633802817 
0.2 0.6 0.2 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.8383838383838383 0.0707070707070707 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.898989898989899 0.0707070707070707 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<TABLE>
0.0707070707070707 0.898989898989899 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.797979797979798 0.1111111111111111 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.797979797979798 0.1111111111111111 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</FOR>
<TABLE>
0.8585858585858586 0.050505050505050504 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Exogenous spending</FOR>
<TABLE>
0.797979797979798 0.1111111111111111 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</FOR>
<TABLE>
0.5959595959595959 0.1717171717171717 0.23232323232323232 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Capital-labour ratio</FOR>
<TABLE>
0.13131313131313133 0.7777777777777778 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<TABLE>
0.0707070707070707 0.8787878787878788 0.050505050505050504 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.8383838383838383 0.0707070707070707 0.09090909090909091 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Lending interest rate (%) [FR.INR.LEND]</FOR>
<TABLE>
0.9595959595959596 0.010101010101010102 0.030303030303030304 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<GIVEN>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</GIVEN>
<GIVEN>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</GIVEN>
<GIVEN>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</GIVEN>
<TABLE>
0.7333333333333333 0.2 0.06666666666666667 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.7142857142857143 0.14285714285714285 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.1111111111111111 0.5555555555555556 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.046153846153846156 0.015384615384615385 0.9384615384615385 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.898989898989899 0.0707070707070707 0.030303030303030304 
</TABLE>
</DEFINITION>
</NETWORK>
</BIF>
