<?xml version="1.0"?>
<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	      <!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
	      <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>smets woulters data-weka.filters.unsupervised.instance.SubsetByExpression-ECLASS is &apos;PRI&apos;-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R6-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R2-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R5-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R6-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R9-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R10-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R14-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R15-unset-class-temporarily-weka.filters.unsupervised.attribute.Reorder-R3,2,7,15,5-6,13,10-11,16,1,12,4,8,14,9-weka.filters.unsupervised.attribute.ReplaceMissingValues</NAME>
<VARIABLE TYPE="nature">
<NAME>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-217,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>&apos;(-inf-6418905054.666666]&apos;</OUTCOME>
<OUTCOME>&apos;(6418905054.666666-9004652527.333332]&apos;</OUTCOME>
<OUTCOME>&apos;(9004652527.333332-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (0,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-4365488000]&apos;</OUTCOME>
<OUTCOME>&apos;(4365488000-8334376000]&apos;</OUTCOME>
<OUTCOME>&apos;(8334376000-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</NAME>
<OUTCOME>&apos;(-inf-84.966667]&apos;</OUTCOME>
<OUTCOME>&apos;(84.966667-85.533333]&apos;</OUTCOME>
<OUTCOME>&apos;(85.533333-inf)&apos;</OUTCOME>
<PROPERTY>position = (-435,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>&apos;(-inf-6418905054.666666]&apos;</OUTCOME>
<OUTCOME>&apos;(6418905054.666666-9004652527.333332]&apos;</OUTCOME>
<OUTCOME>&apos;(9004652527.333332-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-362,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-4365488000]&apos;</OUTCOME>
<OUTCOME>&apos;(4365488000-8334376000]&apos;</OUTCOME>
<OUTCOME>&apos;(8334376000-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Lending interest rate (%) [FR.INR.LEND]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-272,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (0,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-362,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-652,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Capital-labour ratio</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-816,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-725,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP (constant LCU) [NY.GDP.MKTP.KN]</NAME>
<OUTCOME>&apos;(-inf-4719700336.751368]&apos;</OUTCOME>
<OUTCOME>&apos;(4719700336.751368-7953974861.386834]&apos;</OUTCOME>
<OUTCOME>&apos;(7953974861.386834-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Exogenous spending</NAME>
<OUTCOME>&apos;(-inf-6519171629.5859]&apos;</OUTCOME>
<OUTCOME>&apos;(6519171629.5859-9031814883.9473]&apos;</OUTCOME>
<OUTCOME>&apos;(9031814883.9473-inf)&apos;</OUTCOME>
<PROPERTY>position = (-870,384)</PROPERTY>
</VARIABLE>
<DEFINITION>
<FOR>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<TABLE>
0.2727272727272727 0.15151515151515152 0.5757575757575758 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.5353535353535354 0.1111111111111111 0.35353535353535354 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</FOR>
<TABLE>
0.13131313131313133 0.797979797979798 0.0707070707070707 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<TABLE>
0.2727272727272727 0.15151515151515152 0.5757575757575758 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.5353535353535354 0.1111111111111111 0.35353535353535354 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Lending interest rate (%) [FR.INR.LEND]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Capital-labour ratio</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP (constant LCU) [NY.GDP.MKTP.KN]</FOR>
<GIVEN>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</GIVEN>
<GIVEN>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</GIVEN>
<GIVEN>Exogenous spending</GIVEN>
<TABLE>
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.7142857142857143 0.14285714285714285 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.09090909090909091 0.09090909090909091 0.8181818181818182 
0.4482758620689655 0.5172413793103449 0.034482758620689655 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.09090909090909091 0.8181818181818182 0.09090909090909091 
0.2 0.2 0.6 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.7777777777777778 0.037037037037037035 0.18518518518518517 
0.1111111111111111 0.1111111111111111 0.7777777777777778 
0.06666666666666667 0.06666666666666667 0.8666666666666667 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.1111111111111111 0.1111111111111111 0.7777777777777778 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Exogenous spending</FOR>
<TABLE>
0.6363636363636364 0.15151515151515152 0.21212121212121213 
</TABLE>
</DEFINITION>
</NETWORK>
</BIF>
