<?xml version="1.0"?>
<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE BIF [
	<!ELEMENT BIF ( NETWORK )*>
	      <!ATTLIST BIF VERSION CDATA #REQUIRED>
	<!ELEMENT NETWORK ( NAME, ( PROPERTY | VARIABLE | DEFINITION )* )>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT VARIABLE ( NAME, ( OUTCOME |  PROPERTY )* ) >
	      <!ATTLIST VARIABLE TYPE (nature|decision|utility) "nature">
	<!ELEMENT OUTCOME (#PCDATA)>
	<!ELEMENT DEFINITION ( FOR | GIVEN | TABLE | PROPERTY )* >
	<!ELEMENT FOR (#PCDATA)>
	<!ELEMENT GIVEN (#PCDATA)>
	<!ELEMENT TABLE (#PCDATA)>
	<!ELEMENT PROPERTY (#PCDATA)>
]>


<BIF VERSION="0.3">
<NETWORK>
<NAME>smets woulters data-weka.filters.unsupervised.instance.SubsetByExpression-ECLASS is &apos;VCT&apos;-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R1-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R2-weka.filters.unsupervised.attribute.Remove-R6-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R1-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R3-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R4-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R6-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R7-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R8-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R10-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R12-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R13-unset-class-temporarily-weka.filters.unsupervised.attribute.Discretize-B3-M-1.0-R14-unset-class-temporarily-weka.filters.unsupervised.attribute.Reorder-R16,5,9,14,11,2,7,1,10,8,4,6,3,12-13,15-weka.filters.unsupervised.attribute.ReplaceMissingValues</NAME>
<VARIABLE TYPE="nature">
<NAME>Exogenous spending</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-870,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (0,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-362,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>&apos;(-inf-25506661.728395]&apos;</OUTCOME>
<OUTCOME>&apos;(25506661.728395-48298508.641975]&apos;</OUTCOME>
<OUTCOME>&apos;(48298508.641975-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (0,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (0,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>&apos;(-inf--19381666.17284]&apos;</OUTCOME>
<OUTCOME>&apos;(-19381666.17284--5592964.567901]&apos;</OUTCOME>
<OUTCOME>&apos;(-5592964.567901-inf)&apos;</OUTCOME>
<PROPERTY>position = (-217,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</NAME>
<OUTCOME>&apos;(-inf-75.133334]&apos;</OUTCOME>
<OUTCOME>&apos;(75.133334-76.266668]&apos;</OUTCOME>
<OUTCOME>&apos;(76.266668-inf)&apos;</OUTCOME>
<PROPERTY>position = (-435,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-206616666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(206616666.666667-379353333.333333]&apos;</OUTCOME>
<OUTCOME>&apos;(379353333.333333-inf)&apos;</OUTCOME>
<PROPERTY>position = (-544,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</NAME>
<OUTCOME>&apos;(-inf-206616666.666667]&apos;</OUTCOME>
<OUTCOME>&apos;(206616666.666667-379353333.333333]&apos;</OUTCOME>
<OUTCOME>&apos;(379353333.333333-inf)&apos;</OUTCOME>
<PROPERTY>position = (-725,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Lending interest rate (%) [FR.INR.LEND]</NAME>
<OUTCOME>&apos;(-inf-9.958333]&apos;</OUTCOME>
<OUTCOME>&apos;(9.958333-11.416667]&apos;</OUTCOME>
<OUTCOME>&apos;(11.416667-inf)&apos;</OUTCOME>
<PROPERTY>position = (-272,0)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</NAME>
<OUTCOME>&apos;(-inf-2694268571]&apos;</OUTCOME>
<OUTCOME>&apos;(2694268571-5561898337]&apos;</OUTCOME>
<OUTCOME>&apos;(5561898337-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,512)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</NAME>
<OUTCOME>&apos;(-inf-25506661.728395]&apos;</OUTCOME>
<OUTCOME>&apos;(25506661.728395-48298508.641975]&apos;</OUTCOME>
<OUTCOME>&apos;(48298508.641975-inf)&apos;</OUTCOME>
<PROPERTY>position = (-652,384)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</NAME>
<OUTCOME>&apos;(-inf--19381666.17284]&apos;</OUTCOME>
<OUTCOME>&apos;(-19381666.17284--5592964.567901]&apos;</OUTCOME>
<OUTCOME>&apos;(-5592964.567901-inf)&apos;</OUTCOME>
<PROPERTY>position = (-362,256)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>GDP (constant LCU) [NY.GDP.MKTP.KN]</NAME>
<OUTCOME>&apos;(-inf-795901598.96427]&apos;</OUTCOME>
<OUTCOME>&apos;(795901598.96427-1263780697.92854]&apos;</OUTCOME>
<OUTCOME>&apos;(1263780697.92854-inf)&apos;</OUTCOME>
<PROPERTY>position = (0,128)</PROPERTY>
</VARIABLE>
<VARIABLE TYPE="nature">
<NAME>Capital-labour ratio</NAME>
<OUTCOME>Q1</OUTCOME>
<OUTCOME>Q2</OUTCOME>
<OUTCOME>Q3</OUTCOME>
<PROPERTY>position = (-816,0)</PROPERTY>
</VARIABLE>
<DEFINITION>
<FOR>Exogenous spending</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.8585858585858586 0.0707070707070707 0.0707070707070707 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Compensation of employees (current LCU) [GC.XPN.COMP.CN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Final consumption expenditure (constant LCU) [NE.CON.TOTL.KN]</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<GIVEN>Lending interest rate (%) [FR.INR.LEND]</GIVEN>
<GIVEN>Previous Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</GIVEN>
<GIVEN>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</GIVEN>
<TABLE>
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.6 0.2 0.2 
0.1111111111111111 0.3333333333333333 0.5555555555555556 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.1111111111111111 0.5555555555555556 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.1111111111111111 0.1111111111111111 0.7777777777777778 
0.07692307692307693 0.07692307692307693 0.8461538461538461 
0.1111111111111111 0.1111111111111111 0.7777777777777778 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.0196078431372549 0.0196078431372549 0.9607843137254902 
0.2727272727272727 0.09090909090909091 0.6363636363636364 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Wage and salaried workers, total (% of total employed) [SL.EMP.WORK.ZS]</FOR>
<TABLE>
0.030303030303030304 0.010101010101010102 0.9595959595959596 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.6363636363636364 0.1717171717171717 0.1919191919191919 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Gross capital formation (current LCU) [NE.GDI.TOTL.CN]</FOR>
<TABLE>
0.6363636363636364 0.1717171717171717 0.1919191919191919 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Lending interest rate (%) [FR.INR.LEND]</FOR>
<TABLE>
0.25252525252525254 0.1717171717171717 0.5757575757575758 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Inflation, consumer prices (annual %) [FP.CPI.TOTL.ZG]</FOR>
<TABLE>
0.7777777777777778 0.1717171717171717 0.050505050505050504 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</FOR>
<TABLE>
0.8585858585858586 0.0707070707070707 0.0707070707070707 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Previous Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</FOR>
<TABLE>
0.030303030303030304 0.0707070707070707 0.898989898989899 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>GDP (constant LCU) [NY.GDP.MKTP.KN]</FOR>
<GIVEN>Portfolio Investment, net (BoP, current US$) [BN.KLT.PTXL.CD]</GIVEN>
<GIVEN>Net capital account (BoP, current US$) [BN.TRF.KOGT.CD]</GIVEN>
<TABLE>
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
0.3333333333333333 0.3333333333333333 0.3333333333333333 
0.2 0.2 0.6 
0.620253164556962 0.34177215189873417 0.0379746835443038 
0.1111111111111111 0.1111111111111111 0.7777777777777778 
0.14285714285714285 0.14285714285714285 0.7142857142857143 
</TABLE>
</DEFINITION>
<DEFINITION>
<FOR>Capital-labour ratio</FOR>
<TABLE>
0.9797979797979798 0.010101010101010102 0.010101010101010102 
</TABLE>
</DEFINITION>
</NETWORK>
</BIF>
